### PR TITLE
magit-todos-scanner: support LaTex macros

### PR DESCRIPTION
**Pull request by stettberger**
Add support to the todo scanner regex to search for LaTeX macros, which
indicate inline todos. For example:

```latex
\FIXME{Make my reviewer happy!}
```

### CODE REVIEW

**Comment by stettberger** [comment]
After fiddling around a little bit with this idea, I see the problem, that we cannot match the closing `}`, if we only introduce a prefix regex. However, I usually place these todo items in the normal text. [I also have the problem of having multiple todos in one line:

```latex
 \FIXME{task 1}\TODO{I should add something here}
```

Another flexible solution would be to add a fully customizable regular expression. I don't know how this would work out with the search vs. result regexp as it would be cumbersome to specify two regular expressions.

**Comment by alphapapa** [comment]
1.  You could add an additional suffix regexp variable.
2.  I don't know about matching multiple items on a single line.  In theory it should work...

> Another flexible solution would be to add a fully customizable regular expression. I don't know how this would work out with the search vs. result regexp as it would be cumbersome to specify two regular expressions.

With a prefix, keyword, keyword suffix, and a description suffix, it would essentially be fully customizable.    I don't think it would be a good idea to replace the existing regexps with a single one, because it makes the common case much more complicated for the sake of unusual ones like this.

An alternative you might consider would be to write a custom scanner function to find matches in your LaTeX docs and use that as the scanner function in those documents/directories instead of customizing the regexps.

**Comment by stettberger** [comment]
So what would be the pattern order of regular expressions?

            |<KeywordPrefix><Keyword><Keyword Suffix><Description Suffix>
    Default |   -          | TODO   | "(USER)"?        | :(.*)\n
    Org     | [*]*\s       | TODO   | "(USER)"?        |  (.*)\n
    Latex   | "\\"         | TODO   | "[USER]"?        | {([^}]*)}\n

Things to consider:
  - It would be great, if the user could set groups in any of the regex groups from any regex (like the org nesting level). Problem is to implement the description suffix for preview. How do we fill `(group-n 5 ..` there?
  - Why do we have two different regular expressions? One for search and one for extracting the results? They are quite similar. Couldn't we just search for keywordprefix and keyword with the external tool and the use emacs regexs for the rest?

**Comment by alphapapa** [comment]
> * It would be great, if the user could set groups in any of the regex groups from any regex (like the org nesting level). Problem is to implement the description suffix for preview. How do we fill `(group-n 5 ..` there?

I don't understand what you mean.

> * Why do we have two different regular expressions? One for search and one for extracting the results? They are quite similar.

One is for the scanner, the other is for Emacs to match results from the scanner.

> * Couldn't we just search for keywordprefix and keyword with the external tool and the use emacs regexs for the rest?

That's basically what it already does.  Take a look at the code.  :)

**Comment by stettberger** [comment]
I already took a look at the code. I sketched out the approach that I think is most flexible. The current pull request is not feautre complete at the moment, as the help texts are missing and misleading.

**Comment by alphapapa** [comment]
I appreciate your work here.  This will need to be considered carefully, and I may not have time to do so for a few weeks, at least.

In the meantime, some initial thoughts:

* Despite the lisp-based `rx` regexps, I'm reluctant to modify them like this.  I don't feel like this reduces complexity, but rather increases it.  
* Very few users would need or want to modify regexp parts in this way.  I don't mean to downplay your needs, but considering the whole user base, I feel like this adds significant complexity for little benefit, or at least a benefit that very few users would need.
* I think a more generalized approach would be to support multiple scanner functions which could be specialized by filetype and/or filename.  This would allow users to supply their own scanner functions to replace or supplement the default ones in certain directories.  They could even be supplied as add-on packages, like a `magit-todos-latex` package.  Then the results of all the appropriate scanner functions could be combined.  In other words, I think it would be cleaner to extend and customize with additional scanner functions rather than combining more regexp parts into all-encompassing regexps.  It would definitely be a more idiomatic, lispy solution.
* Alternatively, rather than using multiple scanner functions, functions could be called to supply appropriate regexps for certain files, and the configured scanner could be called multiple times, once for each regexp, ideally in parallel.  This might be a better solution, because it would avoid requiring users to define scanners for specific backends, which we have already done.  In this case, the scanner definitions would need to be extended to exclude and include certain filename patterns; we would want to avoid compiling a list of files to scan in Emacs, as that would be slow in larger projects.
* Another possibility would be to factor out scanning into another package altogether, which could be extended and customized without affecting `magit-todos` directly.  That would be a substantial amount of work, but it could be the cleanest approach, and it might benefit other projects as well.  
*  Or, maybe a solution like that already exists that we could adopt.  In a sense, the built-in Emacs `grep` backend is that, but as you can see from the code, it isn't simple to integrate.  So a package that supported multiple scanner backends, customizeable with certain regexps for certain filetypes, and provided the results to packages like `magit-todos`, could be useful.  I don't think I am interested in maintaining such a package myself, but if one existed, I'd be willing to consider using it.

What do you think?

Thanks.

**Comment by stettberger** [comment]
> I appreciate your work here. This will need to be considered carefully, and I may not have time to do so for a few weeks, at least.

I'm also not 100% happy with the current state of the patch. However, I think there are already some very important aspects here.

My overall goal is to provide a flexible mechanism for the user to define his own search expressions and capture the correct information from it.
Thereby, the performance may not suffer is the supplied pattern is efficient (as in: the regular expression behaves good).

> In the meantime, some initial thoughts:
>
>     * Despite the lisp-based `rx` regexps, I'm reluctant to modify them like this.  I don't feel like this reduces complexity, but rather increases it.

I think that the user should only have to define his search pattern once, as otherwise patterns for search and for results will diverge.
If that happens, the user gets misterious "it does not find my TODOs, help!".

We have two kinds of matchers here. The PCRE matchers do not support named or numbered groups (as far as I know). However, we need them to extract the correct information from it to fill the magit-todos-item object. Therefore, we need some kind of translation. And if machines are able to do that, let them do what they are supposed to do.

In the end, a regular expression is just a very simple programming language, and source to source transformation is no black magic. And magit-todos already uses this technique but hides it in calls to rx.el and rxt-... function calls.

>     * Very few users would need or want to modify regexp parts in this way.  I don't mean to downplay your needs, but considering the whole user base, I feel like this adds significant complexity for little benefit, or at least a benefit that very few users would need.

I did not know I wanted the fold by group feature before I saw it. And at least one of my colleagues is eager already eager to see this feature merged. But sure, you never know how many people will use a feature.

The principle operation that magit-todos performs is to find tagged one-line notes within a repository. And it already support different styles of TODO notes (org + non-org). Why? Because Org mode is standard for the emacs environment.

However. Why is there no support for org check boxes? Or for unit-test tool output in crazy XML formats?

>     * I think a more generalized approach would be to support multiple scanner functions which could be specialized by filetype and/or filename.  This would allow users to supply their own scanner functions to replace or supplement the default ones in certain directories.  They could even be supplied as add-on packages, like a `magit-todos-latex` package.  Then the results of all the appropriate scanner functions could be combined.  In other words, I think it would be cleaner to extend and customize with additional scanner functions rather than combining more regexp parts into all-encompassing regexps.  It would definitely be a more idiomatic, lispy solution.

I really would like to run exactly one matcher. With rx, we could combine multiple regular expressions from different scanner objects into one PCRE. However, I dislike the idea to provide fixed bundles of matcher+regular expression as both parts are orthogonal (most of the time). Normally each regular expression, if translated to PCRE, will work with any matcher.


>     * Alternatively, rather than using multiple scanner functions, functions could be called to supply appropriate regexps for certain files, and the configured scanner could be called multiple times, once for each regexp, ideally in parallel.  This might be a better solution, because it would avoid requiring users to define scanners for specific backends, which we have already done.  In this case, the scanner definitions would need to be extended to exclude and include certain filename patterns; we would want to avoid compiling a list of files to scan in Emacs, as that would be slow in larger projects.

Let's try to do it with one external tool invocation. I do not want to grep my 1GB repos more often.

>     * Another possibility would be to factor out scanning into another package altogether, which could be extended and customized without affecting `magit-todos` directly.  That would be a substantial amount of work, but it could be the cleanest approach, and it might benefit other projects as well.

That sounds like the second system effect. I understand the impulse, but it is probably overkill for the problem/

>     * Or, maybe a solution like that already exists that we could adopt.  In a sense, the built-in Emacs `grep` backend is that, but as you can see from the code, it isn't simple to integrate.  So a package that supported multiple scanner backends, customizeable with certain regexps for certain filetypes, and provided the results to packages like `magit-todos`, could be useful.  I don't think I am interested in maintaining such a package myself, but if one existed, I'd be willing to consider using it.

I don't know of any such package.

**Comment by stettberger** [comment]
Perhaps I want to have something like:

```elisp
(magit-todos-pattern "latex"
   :files   '(seq (or ".tex" ".sty" ".ltx") eol)
   :pattern `(seq
              (*? not-newline) "\\"
              (* blank)
              (optional
               (seq "[" (group-n :prefix (1+ (not (any "]")))) "]"))
              ;; Keyword
              (group (or ,@(magit-todos-keywords-list)))
              (*? blank)
              "{" (group-n :description (1+ (not (any "}")))) "}")
   :format nil)
```

**Comment by alphapapa** [comment]
> Perhaps I want to have something like:

I like the way that looks.  However, my concerns about complicating the package remain.  If you want to write a patch that cleanly implements a pattern-definer like that, I'll be happy to consider merging it, but I can't promise that I will.

Like I mentioned before, I think that would fit well into a purpose-specific library to match regexps in certain files, which this package could then depend on as a backend.

I wonder if existing packages, like some of the "tags" packages that scan for language constructs, could be used for that purpose.

**Comment by stettberger** [comment]
As my time is precious, I think I'm happy with the status quo. I have my fork that supports my needs. Merge it if you like, I have invested enough tought and ideas. But I will not invest more time into this as the framing about what is too complex is not well defined.

**Comment by alphapapa** [comment]
Having a little time away from this PR, I looked at it again.  I appreciate your thoughtful work on it.  At this time I don't want to add this additional complexity to the code, especially since only one user has indicated it's needed.  But if other users ask for it or some other factors come to light, I'd be willing to consider merging it in some form.  So the code may be useful someday (and I guess you're already using it, which is great).

Thanks.

**Pull request closed without merging**
