### PR TITLE
For #13: option to visit containing buffer in other window.

### PR DESCRIPTION
**Pull request by zhaojiangbin**

### CODE REVIEW

**Comment by alphapapa** [comment]
Thanks.  A few thoughts:

* Instead of using a boolean to choose whether to open in a new window, it would be better to use `funcall` to call a function set in a `defcustom ... :type 'function`.  That way users can use a variety of functions rather than only these two.
* But before adding such an option, I think we should try using `magit-display-buffer` and `magit-display-file-buffer-function`.  If one of those works, we can avoid adding another option.
* I'd rather not have an option for recentering.  Instead, users could easily add `:after` function advice in their own config that calls `recenter`.  Or they could use a custom function for the previous option that recenters.

What do you think?

**Comment by zhaojiangbin** [comment]
I agree that it'd be better if this can be done using a magit function. I can keep this change to myself while waiting for the real fix.

As for option for recentering, I don't quiet understand. To what function would a user add the `:after` advice, `magit-todos--goto-item`? Is it part of the public interface for customization?

**Comment by alphapapa** [comment]
> I agree that it'd be better if this can be done using a magit function. I can keep this change to myself while waiting for the real fix.

Ok, I'll see what I can come up with.

> As for option for recentering, I don't quiet understand. To what function would a user add the :after advice, magit-todos--goto-item?

Yes, after that function.  

>  Is it part of the public interface for customization?

Well, it's Emacs, so that doesn't really matter.  :)

**Comment by zhaojiangbin** [comment]
Nice.

By the way, are you interested in reviewing changes that allow to use `git-grep`? I added a new choice for `magit-todos-scan-fn`, namely `magit-todos--git-grep-scan-async`, and its callback. Basically I derived the implementation from the existing ones with the result regexp and command line arguments adapted for `git-grep`. The implementation feels a bit of 'copy-and-paste'ish to be honest.

I have both `ag` and `rg` installed in my laptop. But I think this package being an addon to magit, being able to use `git-grep` is still desirable. And `git-grep` is fast, too.

I made a mistake not starting this implementation on top of your master branch so it is not "pull request-ready". But it should be easy to fix for pull if you like the changes.

**Comment by alphapapa** [comment]
Yes, that sounds very interesting.  I'm not sure why I didn't consider `git grep` myself.  Like you said, it must work, since it's part of `git`.  It might make sense for it to replace the find-grep code (which I spent some time banging my head against, but perhaps in vain).

> I made a mistake not starting this implementation on top of your master branch so it is not "pull request-ready". But it should be easy to fix for pull if you like the changes.

You should be able to rebase it on top of `master`.  Magit makes that easy.  :)

I look forward to seeing that PR!  Thanks.

**Comment by zhaojiangbin** [comment]
> I look forward to seeing that PR! Thanks.

Been busy with work today. Will see if I can get some time tomorrow.

**Pull request closed without merging**
