### PR TITLE
Add a gif to show what things should look like when working.

### PR DESCRIPTION
**Pull request by smurphy8**
Didn't know if it would be useful or not but here is a gif what things should look like.

### CODE REVIEW

**Comment by alphapapa** [comment]
Thanks, that's a cool way to illustrate how dynamic it is.

One small issue: in the GIF, the filename has a `./` prefix because you're using the `find` scanner.  Would you be able to redo the animation using the `git grep` or `rg` scanner, which would not display that prefix?  If that's not too much trouble, I'd be glad to add this to a new screenshots page, along with some of the other screenshots (5 is probably too many for the first page anyway).

**Comment by smurphy8** [comment]
Okay I went to redo but I noticed I already had rg selected as that scanner:

```
Its value is ‘magit-todos--scan-with-rg’
Original value was nil
```

**Comment by alphapapa** [comment]
Hm, that's interesting.  I haven't seen `rg` prefix filenames like that.  Have you customized any `magit-todos` options in that repo?

**Comment by smurphy8** [comment]
Not at that point, now I have gotten rid of the colon requirement.

**Comment by alphapapa** [comment]
Are you on Windows or Linux or Mac?

**Comment by smurphy8** [comment]
Linux

**Comment by alphapapa** [comment]
Hm, that's interesting.  What version of `rg` do you have?

**Comment by smurphy8** [comment]
0.10.0

**Comment by alphapapa** [comment]
@smurphy8 Ping?  :)

**Comment by smurphy8** [comment]
I don't see it referenced https://github.com/BurntSushi/ripgrep/blob/master/CHANGELOG.md

**Comment by alphapapa** [comment]
Thanks, I will go ahead and add this to the docs soon.

**Comment by alphapapa** [comment]
Looking at this again, I don't think I should add it to the readme as-is, for a few reasons:

* The GIF shows the menu bar and part of the screen outside of the Emacs window.
* It's a large image relative to the other screenshots in the readme.  It would get scaled down on the rendered page, which would make it blurry and hard to read.
* It still has that `./` prefix on the filenames.

It's a nice idea, to show the item being added and removed, but I'm not sure it's necessary to demonstrate that.  And there are already, perhaps, too many screenshots in the readme.

If you want to tidy it up a bit more, I'd be willing to put it on a separate page with additional screenshots.  But I don't expect you to want to work on it more.

What do you think?

Regardless, thanks for your work and your patience.

**Comment by smurphy8** [comment]
I do think some sort of reference of what things should look like when working would be nice, but if you don't want it I understand.

I really like magit-todos!

**Comment by alphapapa** [comment]
That's a good point.  I'll put it on the to-do list.  Thanks.

**Pull request closed without merging**
