### PR TITLE
Add: Dedicated to-do list buffer

### LINKED ISSUE #35: Command to show items in separate buffer
From @tarsius in #34:

> (Also is there a command to show the list of todos in a separate buffer? The amount of boilerplate that magit would require you to write for this is minimal, basically magit-todos-mode and magit-todos-refresh-buffer.)

### PR DESCRIPTION
**Pull request by alphapapa**
Closes #35.  Thanks to Jonas Bernoulli (@tarsius).

### CODE REVIEW

**Comment by alphapapa** [comment]
@tarsius I tried to implement this by reusing as much functionality built-in to Magit as possible. It seems to work well, but I'm not sure if it's proper to:

1.  Inherit from magit-status-mode: Should I inherit from magit-mode instead?
2.  Use magit-insert-status-headers: I think the headers are necessary and useful, and probably fine here.

Thanks.

**Comment by tarsius** [comment]
Since you do (2), (1) is probably the right thing to do, but not that there are some `(derived-mode-p 'magit-status-mode)`, which might or might not trigger undesired behavior.

**Comment by alphapapa** [comment]
Thanks, that's what I thought.  I'll go ahead and merge this now but hold off on making a stable release until it's tested a bit (not that a significant number of users use the stable version anyway, haha).

**Comment by alphapapa** [comment]
As a note mostly to myself: another benefit from inheriting from `magit-status-mode` is that users who customize dir-local variables for this package only have to do so for that mode, rather than having to also do it for `magit-todos-list-mode`.

**Pull request merged**
