### PR TITLE
Add a defcustom to restrict or disable repo-wide scans

### PR DESCRIPTION
**Pull request by DMRobertson**
This allows you to disable potentially expensive repo-wide scans in lieu of the branch-diff specific
scans introduced in 6d590872dab914908b539c54da2c68dc75491e93.

(Not very experienced with elisp, so all advice is gratefully received!)

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi David,

I appreciate your work here.  Before merging an option like this, let's talk about the problem.  Are you having problems with expensive scans in large repos?  There are ways to mitigate that, including using a different scanner, setting a max depth, and disabling automatic scans.  If you want only the diff scanner to be used in a repo, you can set a dir-local variable to use that scanner in that repo.

Maybe what's needed is a more powerful UI for changing options in specific repos.  There's an issue where making a Magit-style popup is being discussed.

Thanks.

**Comment by DMRobertson** [comment]
I don't think there's a particular problem as such; it's more that I want to tweak things to fit my workflow. I can see that this PR is the tail wagging the dog a bit... but let's see if I can pin down my situation.

At work our source tree is one large(?) svn repository, with a checkout totalling about 16GB last time I checked. We mostly use git-svn to make local commits, and a few of us use magit and emacs for day-to-day work. I thought I'd give magit-todos a try. I had a few issues at first. Performance was one, but once I'd set ignore globs to only scan the parts of the repo that I work in, performance with ripgrep was okay. I also bumped into issue #63 in a few places. I didn't have a very good way of working out which files were a problem---maybe I need to take a look at the comments in that issue again.

What I'm looking for is a way to track "what have I done and what needs to be done on this feature branch"? I've got into the habit of refreshing the magit-status buffer to see what unstaged changes I've made locally. That's great for the former for reviewing what I've done, but not so good for working out what's left to be done. I'm mostly looking to track a few (say max 20) personal `// TODO`s or `//NOTE`s---using the project-wide scanner would be overkill for that. Even then it's hard to find my own to-dos amidst several thousand that have accumulated across the whole repository!.

All of this meant that the latest release with the branch-specific diff scanner was exactly what I was looking for. For me personally, the whole repo todo-list is too large in scope to be useful as part of the magit-status buffer. So I just wanted to expose the branch-specific functionality. With all that said, I have a few smaller private repos at work for one-off scripts and various dotfiles. I can see that a project-wide scanner would be good to have in the status buffer there---when to-dos are more of a wish list than a task list.

It sounds like a dir-local variable to only use the branch diff scanner is what I want. I though that the scanner was just *how* files are searched (e.g. ripgrep, git grep, GNU grep), but it seems like the scanner also controls *what* is searched, as in e.g. `(magit-todos-defscanner "git diff" ...)`. Thanks also for flagging up the max-depth and disabling automatic scan options---I'll take a look at those.

**Comment by alphapapa** [comment]
> Even then it's hard to find my own to-dos amidst several thousand that have accumulated across the whole repository!.

Note that you can use syntax like `TODO(dmrobertson): My task` to annotate tasks with a string like your name, and then sort/group by that.

> it seems like the scanner also controls what is searched

Not exactly.  The `git diff` scanner is a special case that isn't intended to be used as the only scanner--but if that's what you need, you can do so.

**Comment by alphapapa** [comment]
@DMRobertson Do you have any more thoughts about this PR?

**Comment by DMRobertson** [comment]
@alphapapa not particularly. I haven't got round to trying magit-todos again. (Maybe when I next get the urge/chance to fiddle around with my configuration!) It sounds like your suggestions will work for me though. Thanks again!

**Pull request closed without merging**
